freebooks/books/urls.py
from django.conf.urls import url
from . import views

app_name = 'books'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^books/$', views.IndexView.as_view(), name='index'),
    url(r'^books/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^books/(?P<book_id>[0-9]+)/download/$', views.pdf_download, name='download'),
]

freebooks/freebooks/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('books.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

freebooks/books/models.py
from django.db import models


class Category(models.Model):
    category_id = models.AutoField(primary_key=True, max_length=10)
    category_title = models.CharField(max_length=250)

    def __str__(self):
        return self.category_title


class Author(models.Model):
    author_id = models.AutoField(primary_key=True, max_length=10)
    author_name = models.CharField(max_length=250)

    def __str__(self):
        return self.author_name


class Publisher(models.Model):
    publisher_id = models.AutoField(primary_key=True, max_length=10)
    publisher_name = models.CharField(max_length=250)

    def __str__(self):
        return self.publisher_name


class Book(models.Model):
    book_id = models.AutoField(primary_key=True, max_length=10)
    book_category = models.ForeignKey(Category, on_delete=models.CASCADE)
    book_author = models.ForeignKey(Author, on_delete=models.CASCADE)
    book_publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    book_title = models.CharField(max_length=250)
    book_sub_title = models.CharField(max_length=250)
    book_description = models.TextField(null=True, blank=True)
    book_ISBN = models.CharField(max_length=250)
    book_pages = models.CharField(max_length=250)
    book_year = models.CharField(max_length=250)
    book_cover = models.FileField(upload_to='books/cover/', max_length=250)
    book_pdf = models.FileField(upload_to='books/pdf/', max_length=250)

    def __str__(self):
        return self.book_title

freebooks/books/views.py
import string
from django.http import HttpResponse
from django.views import generic
from .models import Category, Author, Book


class IndexView(generic.ListView):

    template_name = 'index.html'
    context_object_name = 'books'
    paginate_by = 1

    def get_queryset(self):
        return Book.objects.all().values('book_id', 'book_title', 'book_cover', 'book_description')


class DetailView(generic.DetailView):

    model = Book
    template_name = 'detail.html'


def pdf_download(request, book_id):
    book = Book.objects.get(pk=book_id)
    book_name = book.book_title.replace(' ', '_')
    response = HttpResponse(book.book_pdf, content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename='+book_name+'.pdf'
    return response

freebooks/books/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/books.css' %}">
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
  </head>
  <body>
    {% block body %}
    {% endblock %}
  </body>
</html>

freebooks/books/templates/detail.html
{% extends 'base.html' %}

{% block title %} Book | {{ book.book_title }} {% endblock %}


{% block body %}
    <div class="container">
        <div class="row margin-top-20">
            <div class="col-md-12">
                <h2>{{ book.book_title }}</h2>
                <h4>{{ book.book_sub_title }}</h4>
            </div>
        </div>
        <div class="row margin-top-20">
            <div class="col-md-3">
                <img src="/uploads/{{ book.book_cover }}" class="book-detail-thumb img-fluid">
            </div>
            <div class="col-md-9">
                <h5>Book Description</h5>
                <p>{{ book.book_description|safe }}</p>
            </div>
        </div>
        <div class="row margin-top-20">
            <div class="col-md-3"></div>
            <div class="col-md-9">
                <h5>Book Details</h5>
                <ul class="book-details">
                    <li>
                        <span class="book-details-title">Category: </span>
                        <span><strong>{{ book.book_category.category_title }}</strong></span>
                    </li>
                    <li>
                        <span class="book-details-title">Author: </span>
                        <span><strong>{{ book.book_author.author_name }}</strong></span>
                    </li>
                    <li>
                        <span class="book-details-title">Publisher: </span>
                        <span><strong>{{ book.book_publisher.publisher_name }}</strong></span>
                    </li>
                    <li>
                        <span class="book-details-title">ISBN: </span>
                        <span><strong>{{ book.book_ISBN }}</strong></span>
                    </li>
                    <li>
                        <span class="book-details-title">Pages: </span>
                        <span><strong>{{ book.book_pages }}</strong></span>
                    </li>
                    <li>
                        <span class="book-details-title">Year: </span>
                        <span><strong>{{ book.book_year }}</strong></span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row margin-top-20">
            <div class="col-md-3"></div>
                <a class="btn btn-lg btn-info" href="{% url 'books:download' book.book_id %}" target="_blank">Downloads</a>
            </div>
        </div>
    </div>
{% endblock %}

freebooks/books/templates/index.html
{% extends 'base.html' %}

{% block title %} Books {% endblock %}

{% block body %}

    <div class="container">
        {% if books %}
            {% for book in books %}
                <div class="row book-list margin-top-20">
                    <div class="col-md-2 text-center">
                        <a href="{% url 'books:detail' book.book_id %}">
                            <img src="/uploads/{{ book.book_cover }}"
                                 class="img-thumbnail"
                                title="{{ book.book_title }}">
                        </a>
                    </div>
                    <div class="col-md-10">
                        <a class="book-detail-link" href="{% url 'books:detail' book.book_id %}">
                            <h3>{{ book.book_title }}</h3>
                        </a>
                        {{ book.book_description|safe|slice:":255" }}
                        <a class="book-detail-link" href="{% url 'books:detail' book.book_id %}">[...]</a>
                    </div>
                </div>
            {% endfor %}

            {% if is_paginated %}
                <div class="pagination">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                            <a href="/books?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                        <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                            <a href="/books?page={{ page_obj.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>
            {% endif %}

        {% else %}
            <h3>Sorry, No Book Available.</h3>
        {% endif %}
    </div>

{% endblock %}